<?php
inc([
    'db',
    'model'
]);
if(isset($_GET['sitea'],$_GET['siteb'],$_GET['dia'])){
    model('site');
    $db=db();
    $dia=$_GET['dia'];
    $siteAIn=$_GET['sitea'];
    $siteAOut=readSite($db,$siteAIn,$dia);
    $siteBIn=$_GET['siteb'];
    $siteBOut=readSite($db,$siteBIn,$dia);
    $data=[
        'title'=>'Cisco',
        'sitea'=>$siteAOut,
        'siteb'=>$siteBOut
    ];
}else{
    $data=[
        'title'=>'Cisco'
    ];
}
view('dois',$data);
