<?php
inc([
    'db',
    'model'
]);
if(isset($_GET['sitea'],$_GET['siteb'])){
    model('site');
    $db=db();
    $siteAIn=@$_GET['sitea'];
    $siteAOut=readSite($db,$siteAIn);
    $siteBIn=@$_GET['siteb'];
    $siteBOut=readSite($db,$siteBIn);
    $data=[
        'title'=>'Cisco',
        'sitea'=>$siteAOut,
        'siteb'=>$siteBOut
    ];
}else{
    $data=[
        'title'=>'Cisco'
    ];
}
view('dois',$data);
