<?php
inc([
    'db',
    'model'
]);
if(isset($_GET['sitea'],$_GET['siteb'])){
    model('sites');
    $db=db();
    $siteAIn=$_GET['sitea'];
    $siteAOut=readSiteMonth($db,$siteAIn);
    $siteBIn=$_GET['siteb'];
    $siteBOut=readSiteMonth($db,$siteBIn);
    $data=[
        'title'=>'Cisco',
        'sitea'=>$siteAOut,
        'siteb'=>$siteBOut
    ];
}else{
    $data=[
        'title'=>'Cisco'
    ];
}
view('index',$data);
